### PR TITLE
Match user pref to recommendation test - closes #50

### LINKED ISSUE #50: UserPref.js state does not match Recommendation_test.js
**Describe the bug**

Although not integrated yet, there will be an error when trying to integrate the UserPref and the Recommendation_Test since the two have different object structures.

On UserPref.js
```
    this.state = {
      sliderCategories: 0.25,
      sliderPriceRange: 0.25,
      sliderRating: 0.25,
      sliderRange: 0.25,
      '4d4b7105d754a06374d81259': true, // this is the food general category in foursquare -- setting as initial state in case there are no food preferences
      distancePreference: 1000,
      sliderPriceTier: 3,
      sliderRatingPref: 7
    }
```
On Recommendation_test.js

```
const dummyUserData = {
  weights: {
    categories: 0.1,
    priceRange: 0.4,
    rating: 0.3,
    range: 0.2
  },
  categories: {
    '4bf58dd8d48988d1d2941735': 0.7,
    '4bf58dd8d48988d1e0931735': 0.7,
    '4bf58dd8d48988d1ca941735': 0.4,
  },
  priceTier: 2,
  rating: 2,
  distance: 5000
}
```

**To Reproduce**
1. Go to UserPref and invoke ```rateVenu(dummyData, this.state)``` where this.state is the UserPref state. 

**Expected behavior**
```rateVenu()``` returns a savor score for each of the items accurately

**Actual behavior**
There will be an error since the two have different data structures.

### PR DESCRIPTION
**Pull request by aminoche**
# What Did You Do?

Brought in a lodash function to ensure the Recommendation_Engine.js file matches the UserPref.js file

# Is It Finished?
Yes

# Did It Break Anything?
It may force the user to go to UserPreferences...but this is ideal for testing it works.

### CODE REVIEW

**Comment by aminoche** [comment]
closes #50

File: components/UserPref.js [hunk 1]
```diff
@@ -147,10 +149,11 @@ class UserPref extends Component {
               <Slider
                 maximumValue={10}
                 minimumValue={0}
-                value={2.5}
+                value={5}
                 step={0.5}
                 onValueChange={value => {
-                  this.checkAndAffect(value, 'sliderCategories')
+                  //this.checkAndAffect(value, 'weights');
```
Comment (aminoche) [inline components/UserPref.js]: Need to remove this comment...

File: components/UserPref.js [hunk 2]
```diff
@@ -305,10 +308,13 @@ class UserPref extends Component {
                 display: 'flex',
                 flexDirection: 'column',
                 justifyContent: 'center'
-              }
-              this.setState(this.state)
-              await this.savePrefs()
-              this.props.navigation.navigate('Main')
+              };
+              this.setState(this.state);
+              console.log('-------STATE-------');
```
Comment (aminoche) [inline components/UserPref.js]: Need to remove these console.logs...
